### PR TITLE
Add chart gallery

### PR DESCRIPTION
**Pull request by hcorson-dosch-usgs**
Changes made:
-----------
This MR adds the USGS Land Change Chart Gallery - adding in a tile in the 'Interactives' section and updating the 'Recent' section at the top of the page

image

image

Testing:
----------------------------
Before making this pull request, I:
- [x] Cleaned the code the way Vue likes it - run 'npm run lint --fix'        
- [ ] Made sure all tests run
- [ ] Ran WAVE plugin 508 compliance tool

I can confirm this has been checked on:
- [x] Chrome
- [ ] Safari
- [x] Edge
- [x] Firefox
- [ ] Samsung Internet
- [ ] Internet Explorer 11 (not supported, but still needs at least a working user redirect page)

### CODE REVIEW

**Review by cnell-usgs — COMMENTED** [review]
SC: Make title "Earth is in flux"

**Comment by hcorson-dosch-usgs** [comment]
Title changed:

image

image

**Comment by cnell-usgs** [comment]
Looks good - but do you want to use the same font as the site for the title on the thumbnail? Or maybe drop the title on it completely. We generally don't include the title on thumbnail, with the exception of the recent "Unequal access to water" site

**Review by cnell-usgs — APPROVED** [review]

**Comment by hcorson-dosch-usgs** [comment]
> Looks good - but do you want to use the same font as the site for the title on the thumbnail? Or maybe drop the title on it completely. We generally don't include the title on thumbnail, with the exception of the recent "Unequal access to water" site

yeah, I can drop it. The same font isn't available in Adobe, for some reason

**Comment by hcorson-dosch-usgs** [comment]
image

**Pull request merged**
